- name: Copy Cloudflare Certbot credentials file
  ansible.builtin.template:
    src: cloudflare/cloudflare-credentials.ini.j2
    dest: /root/cloudflare-credentials.ini
    owner: root
    group: root
    mode: '600'

# We're gonna do wildcard certificates later, but we accidentally maxed out those certs until the 8th due to too many cert requests during testing.
- name: Refresh installed Certbot certs if close to expiry (or not present)
  register: result
  changed_when: '"Certificate not yet due for renewal" not in result.stdout'
  ansible.builtin.command:
    argv: ["certbot", "certonly", "--dns-cloudflare", "--dns-cloudflare-credentials", "/root/cloudflare-credentials.ini", "-nd", "*.{{ hw_url }}", "--cert-name", "{{ hw_url }}"]

- name: Copy main NGINX configuration file
  ansible.builtin.copy:
    src: server/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    mode: '644'
    backup: yes

- name: Copy NGINX service files to server
  changed_when: False
  ansible.posix.synchronize:
    src: server/nginx/sites-enabled/
    dest: /etc/nginx/sites-enabled/
    rsync_opts: ["--delete"]

- name: List NGINX service files on server
  register: nginx_configs
  ansible.builtin.find:
    paths: /etc/nginx/sites-enabled/
    file_type: any
    recurse: no

- name: Ensure NGINX service files have correct permissions
  changed_when: False
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    mode: '644'
  loop: "{{ nginx_configs.files }}"
  loop_control:
    label: "{{ item.path | basename }}"

- name: Restart NGINX systemd service
  changed_when: False
  ansible.builtin.systemd:
    name: nginx
    state: restarted
