# This doesn't work with 'ansible.builtin.script' for some reason, so we use the shorthand 'script'. We'll try to figure out the cause later.
- name: Ensure needed GPG keys are on the system
  changed_when: False
  script: "scripts/add_gpg_key.sh {{ item.url | quote }} {{ item.file_name | quote }}"
  loop: [
    {"url": "https://proget.{{ hw_url }}/debian-feeds/server-packages.pub", "file_name": "/usr/share/keyrings/server-packages-archive-keyring.gpg"}
  ]

- name: Ensure needed APT repositories are present
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  loop: [
    "deb [signed-by=/usr/share/keyrings/server-packages-archive-keyring.gpg] https://proget.{{ hw_url }}/ server-packages main"
  ]

- name: Ensure packages from the server APT repository are installed and at their latest version
  ansible.builtin.apt:
    update_cache: yes
    state: latest
    pkg:
      - docker-compose
      - drone-cli
