# We're gonna do wildcard certificates later, but we accidentally maxed out those certs until the 8th due to too many cert requests during testing.
- name: Refresh installed Certbot certs if close to expiry (or not present)
  tags: ["certbot"]
  register: result
  changed_when: '"Certificate not yet due for renewal" not in result.stdout'
  ansible.builtin.command:
    argv: ["certbot", "certonly", "--dns-cloudflare", "--dns-cloudflare-credentials", "/root/cloudflare-credentials.ini", "-n",
           "-d", "*.{{ hw_url }}", "-d", "{{ hw_url }}", "-d", "*.{{ makedeb_url }}", "-d", "{{ makedeb_url }}", "--cert-name", "homelab"]

- name: Copy main NGINX configuration file
  ansible.builtin.template:
    src: nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    mode: '644'
    backup: yes

- name: Copy NGINX service files to server
  changed_when: False
  ansible.builtin.template:
    src: "nginx/sites-enabled/{{ item }}"
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    owner: root
    group: root
    mode: '644'
  loop:
    - all
    - api.hunterwittenborn.com
    - bitwarden.hunterwittenborn.com
    - cdn.hunterwittenborn.com
    - docs.hunterwittenborn.com
    - docs.makedeb.org
    - drone.hunterwittenborn.com
    - element.hunterwittenborn.com
    - hunterwittenborn.com
    - makedeb.org
    - mailcow.hunterwittenborn.com
    - matrix-admin.hunterwittenborn.com
    - matrix.hunterwittenborn.com
    - mpr.makedeb.org
    - nextcloud.hunterwittenborn.com
    - proget.hunterwittenborn.com
    - shlink-admin.hunterwittenborn.com
    - shlink.hunterwittenborn.com
    - www.hunterwittenborn.com

- name: List NGINX service files on server
  register: nginx_configs
  ansible.builtin.find:
    paths: /etc/nginx/sites-enabled/
    file_type: any
    recurse: no

- name: Ensure NGINX service files have correct permissions
  changed_when: False
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    mode: '644'
  loop: "{{ nginx_configs.files }}"
  loop_control:
    label: "{{ item.path | basename }}"

- name: Restart NGINX systemd service
  changed_when: False
  ansible.builtin.systemd:
    name: nginx
    state: restarted
