- name: Make sure needed packages are installed
  tags: ["scripts"]
  ansible.builtin.apt:
    state: present
    pkg:
      - restic
      - rclone

- name: Create secret hash for Rclone
  tags: ["scripts"]
  register: secret
  ansible.builtin.command:
    argv: ["rclone", "obscure", "{{ restic_rclone_webdav_password }}"]

- name: Setup Rclone config
  tags: ["scripts"]
  ansible.builtin.command:
    argv: [
      "rclone", "config", "create",
      "restic-backup", "webdav",
      "type", "webdav",
      "url", "https://u298543.your-storagebox.de",
      "user", "u298543",
      "pass", "{{ secret.stdout }}",
      "vendor", "other"
    ]

- name: Copy templated scripts
  tags: ["scripts"]
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '700'
  loop: [
    {"src": "scripts/restic-backup.j2", "dest": "/usr/local/bin/restic-backup"},
    {"src": "scripts/docker-pruner.j2", "dest": "/usr/local/bin/docker-pruner"},
    {"src": "scripts/start-services.j2", "dest": "/usr/local/bin/start-services"}
  ]
