---
- name: Deploy homelab
  hosts: homelab
  remote_user: root
  roles:
    - {role: "setup_ssh", users: ["hwittenborn", "sshwifty"]}
    - setup_apt
    - setup_cloudflare
    - setup_scripts
    - setup_cron
    - homelab
